### ISSUE TITLE
Fatal error: nuxt instance unavailable

### ISSUE THREAD

**Issue by FStack-Consulting** [sidebase/nuxt-auth#173]
### Environment

------------------------------
- Operating System: `Windows_NT`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@3.3.1`
- Builder:          `vite`
- User Config:      `alias`, `css`, `build`, `vite`, `srcDir`, `nitro`, `imports`, `runtimeConfig`, `modules`, `auth`
- Runtime Modules:  `@pinia/nuxt@0.4.6`, `@nuxtjs/device@3.0.0`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`
------------------------------

### Reproduction

https://github.com/FStack-Consulting/nuxt-issue/

### Describe the bug

Unable to use when using own login.vue page.
Constantly throws this error when nuxt is running and nuxt-auth doesn't work anymore then.

**Comment by BracketJohn** [comment]
Will look into it, thanks for the repro 🙇

**Comment by f0reclone** [comment]
I had the same error when enabling ssr. Without ssr it works fine.

```
500 nuxt instance unavailable

at Module.useRequestHeaders (./node_modules/nuxt/dist/app/composables/ssr.mjs:7:41)
at getCsrfToken (./node_modules/@sidebase/nuxt-auth/dist/runtime/composables/useSession.mjs:19:44)
at signIn (./node_modules/@sidebase/nuxt-auth/dist/runtime/composables/useSession.mjs:52:27)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async checkCredentials (./pages/login.js:20:30)
at async setup (./pages/login.js:17:93)
```

**Comment by BracketJohn** [comment]
This issue is also related to #178, see #178 for the fix tyhat was also applied to this via #190.

Should be fixed when we merge #190

**Comment by BracketJohn** [comment]
The release for this is out, btw. Checkout the latest `0.4.0-alpha.5`.  Please let me know if the issue was resolved or still occurs, that would be super duper helpful!

Thanks and have a good day (:

**Comment by tonybrown-campbellsci** [comment]
Hi @BracketJohn - Thanks for the hard work and attempted fix.

I can confirm the error is still happening within my site while using `0.4.0-alpha.5`. I noticed the error occurs whenever I attempt to run `npm run build` without the application already running. I assume it has something to do with a protected page forcing a redirect during the setup process.

The error I see is:
```
 ERROR  [nuxt] [request error] [unhandled] [500] 500 Internal Server Error (http://127.0.0.1:3000/api/auth/session?callbackUrl=http://127.0.0.1:3000/about)
  at runMicrotasks (<anonymous>)
  at processTicksAndRejections (node:internal/process/task_queues:96:5)
  at async ./.nuxt/prerender/chunks/app/server.mjs:1507:62
  at async Object.callAsync (./node_modules/unctx/dist/index.mjs:53:16)
  at async applyPlugin (./.nuxt/prerender/chunks/app/server.mjs:120:33)
  at async applyPlugins (./.nuxt/prerender/chunks/app/server.mjs:129:5)
  at async createNuxtAppServer (./.nuxt/prerender/chunks/app/server.mjs:4968:7)
  at async Object.renderToString (./node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
  at async ./.nuxt/prerender/chunks/renderer.mjs:387:21
  at async ./.nuxt/prerender/chunks/renderer.mjs:28:22
```
Of course, the issue is that this occurs during the build process, prior to actually _serving_ the application...

Any help would be appreciated! To confirm, the application is full integrated already and allows provider login on my dev site, but I can't build for production.

Thanks!

**Comment by BracketJohn** [comment]
Hey @tonybrown-campbellsci 👋 

This is a new issue, right? Because: In your error I cannot see anything related to "nuxt instance unavailable". I want to help you though, so can you please:
1. open a new issue for this
2. also provide a reproduction there (can be the same one you posted above of course, if the error occurs there). The reproduction should contain:
  - a repo,
  - steps to take to reproduce that I can follow

**Comment by f0reclone** [comment]
Hey @BracketJohn thanks for fixing the issue. For me it works now :)

**Comment by tonybrown-campbellsci** [comment]
Hello @BracketJohn - I think the solution was to manually enter a secret within the `/server/api/auth/[...].vue` file. I had setup the secret to consume an environment variable, but that wasn't working, which ultimately caused the error reported. I apologize for the confusion as I thought it was related to the issue.

Thanks!

**Comment by BracketJohn** [comment]
sure sure - glad it all worked out, have fun using the library + all the best with the apps you build (:
