### ISSUE TITLE
Error: nuxt instance unavailable

### ISSUE THREAD

**Issue by KoenCa** [sidebase/nuxt-auth#178]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.15.1`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `npm@8.11.0`
- Builder:          `vite`
- User Config:      `nitro`, `app`, `typescript`, `runtimeConfig`, `postcss`, `schemaOrg`, `modules`, `css`, `build`, `auth`
- Runtime Modules:  `@nuxtjs/tailwindcss@6.1.3`, `@vueuse/nuxt@9.5.0`, `@formkit/nuxt@1.0.0-beta.12`, `nuxt-schema-org@1.1.0-beta.6`, `@sidebase/nuxt-auth@0.3.4`
- Build Modules:    `-`
------------------------------

### Describe the bug

Every time the session is refreshed I get the error: `Error: nuxt instance unavailable` in my terminal. Everything seems to work fine though. Not sure if this is a bug or something is configured wrong?

### Additional context

I use the credentials provider together with refresh token logic like the examples in the docs. It also looks like it doesn't happen immediately after logging in, but only after refreshing one or more times and then it keeps happening every session refresh. It occurs on the dev server and the built server. 

### Logs

```shell
[nitro] [dev] [uncaughtException] Error: nuxt instance unavailable                                                                               13:41:30
    at Module.useNuxtApp (.../node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at Module.useRequestEvent (.../node_modules/nuxt/dist/app/composables/ssr.mjs:14:58)
    at Module.getRequestURL (.../node_modules/@sidebase/nuxt-auth/dist/runtime/utils/url.mjs:13:99)
    at getSession (.../node_modules/@sidebase/nuxt-auth/dist/runtime/composables/useSession.mjs:80:53)
    at Timeout._onTimeout (.../node_modules/@sidebase/nuxt-auth/dist/runtime/plugin.mjs:30:9)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by BracketJohn** [comment]
Hey @KoenCa 🧇 

Thanks for the report - can you see if this problem persists on `@sidebase/nuxt-auth@0.4.0-alpha.3`?

**Comment by KoenCa** [comment]
Looks like this problem still persists on that version.

**Comment by KoenCa** [comment]
I also want to point out that it starts happening after refreshing the browser after logging in. So I login, then I can navigate around the website and there will be no error until I refresh the browser or close and open tab page.

**Comment by BracketJohn** [comment]
Thanks!

This should hopefully be fixed by #190, see this line:
https://github.com/sidebase/nuxt-auth/pull/190/files#diff-1cf15bfd1211492fd26076eaba7ee1f9cbc925217d45474642b0cd42c121ba73R187

This is where `getRequestURL` used to be called directly, now we explicitly set the nuxt-context for it

**Comment by KoenCa** [comment]
Hey, I just updated to version `0.4.0` (I cleaned everything before doing this), but this error still keeps showing up in the Nuxt log. Nuxt version is `3.1.2` and Nitro is `2.2.1`.

**Comment by BracketJohn** [comment]
Heya!

Can you share the full error log here? (:

**Comment by KoenCa** [comment]
This is what I see every time the session refreshes:

```
[nitro] [dev] [unhandledRejection] Error: nuxt instance unavailable
    at Module.useNuxtApp (.../node_modules/nuxt/dist/app/nuxt.mjs:165:13)
    at getSession (.../node_modules/@sidebase/nuxt-auth/dist/runtime/composables/useSession.mjs:95:38)
    at Timeout._onTimeout (.../node_modules/@sidebase/nuxt-auth/dist/runtime/plugin.mjs:31:9)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```

**Comment by KoenCa** [comment]
Looks like the latest release `0.4.2` fixed the error thanks to https://github.com/sidebase/nuxt-auth/issues/236 .
